services:
  app:
    build: .
    image: super-auto-pack-builder
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - .:/app
  hadolint:
    image: hadolint/hadolint
    volumes:
      - .:/app
    working_dir: /app